---

- name: Check for valid ssl certificates
  fail:
    msg: 'Please define proper ssl certificates for mailserver'
  when: mailserver_ssl_certificate_key == '' or mailserver_ssl_certificate == ''

- name: Ensure ssl save paths exist
  file:
    path: '{{ mailserver_ssl_certificate_path | dirname }}'
    state: directory
    owner: root
    group: root
    mode: 0440

- name: Copy certificate key
  no_log: true
  template:
    src: 'ssl/certificate_key.pem'
    dest: '{{ mailserver_ssl_certificate_key_path }}'
    owner: root
    group: root
    mode: 0400

- name: Generate certificate.pem
  no_log: true
  template:
    src: 'ssl/certificate.pem'
    dest: '{{ mailserver_ssl_certificate_path }}'
    owner: root
    group: root
    mode: 0400
